services:
  database:
    platform: linux/x86_64
    container_name: LS-Database
    build:
      context: .
      dockerfile: Dockerfile-ls-db
    ports:
      - "3453:3306"
  lobby:
    container_name: LS-api
    build:
      context: .
      dockerfile: Dockerfile-ls-api
    ports:
      - "4242:4242"
    depends_on:
      - database
    command: sh -c "/wait && java -jar /usr/app/ls.jar"
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
  server:
    container_name: Splendor-Server
    build:
      context: .
      dockerfile: Dockerfile-server
      args:
        SAVED_GAMES_PATH: /usr/src/app/saved_games
    ports:
      - "8000:8000"
    depends_on:
      - lobby
    command: sh -c "/wait && java -jar SplendorServer.jar"
    environment:
      - WAIT_HOSTS=lobby:4242
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
      - SAVED_GAMES_PATH=/usr/src/app/saved_games
    volumes:
      - saved_games:/usr/src/app/saved_games
version: '3.8'
volumes:
  saved_games:
