FROM maven:3.6-jdk-13 AS splendor-server-build
# Mount the volume containing the saved games
ENV SAVED_GAMES_PATH /usr/src/app/saved_games
VOLUME $SAVED_GAMES_PATH
COPY server/src /usr/src/app/src
COPY server/pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package -Pprod


## Wait for LS to be ready
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

FROM openjdk:8-jdk-alpine
COPY --from=splendor-server-build /usr/src/app/target/SplendorServer.jar SplendorServer.jar
COPY --from=splendor-server-build /wait /wait

EXPOSE 8080
